# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci:"
      
  - package-ecosystem: "npm"
    directory: "/cra"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(cra):"
      
  - package-ecosystem: "npm"
    directory: "/docusaurus"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(docs):"
      
  - package-ecosystem: "nuget"
    directory: "/dotnet/iwebapiproject"
    schedule:
      interval: "daily"
    commit-message:
      # considered fix because it affects the template itself, not the template package
      prefix: "fix(dotnet):"
      
