stages:
  - build
  - publish
  - docs

build:
  image: node:12
  stage: build
  before_script:
    - npm ci
  script:
    - npm run copy
    - npm run stripTypeScript
  artifacts:
    untracked: true
    exclude:
      - node_modules
    expire_in: 2 weeks
  rules:
    - if: $CI_COMMIT_TAG

publish:
  image: node:12
  stage: publish
  before_script:
    - npm ci
    - echo //${ARTIFACTORY_NPM_REGISTRY}:_authToken=${ARTIFACTORY_NPM_TOKEN} > .npmrc
  script:
    - npx lerna publish from-package --yes
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG

docs:
  image: appropriate/curl:latest
  stage: docs
  script:
    - curl -X POST -k $DOCS_TRIGGER_URL
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - docusaurus/**/*
        - .gitlab-ci.yml