stages:
  - build
  - publish
  - docs

build:
  image: node:12
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - cra-template
      - cra-template-js
    expire_in: 2 weeks
  rules:
    - if: $CI_COMMIT_TAG

publish:
  image: node:12
  stage: publish
  before_script:
    - npm ci
    - echo //${NPM_REGISTRY}:_authToken=${NPM_TOKEN} > .npmrc
    - git update-index --assume-unchanged .npmrc
  script:
    - npx lerna publish from-package --yes
  rules:
    - if: $CI_COMMIT_TAG

docs:
  image: appropriate/curl:latest
  stage: docs
  tags:
    - wip
  script:
    - curl -X POST -k $DOCS_TRIGGER_URL
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - docusaurus/**/*
        - .gitlab-ci.yml
