apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "chart.fullname" . }}-pull-secret
stringData:
  .dockerconfigjson: "{\"auths\":{\"{{ .Values.registry.url }}\":{\"username\":\"{{ .Values.registry.user }}\",\"password\":\"{{ .Values.registry.password }}\"}}}"
