stages:
  - build
  - test
  - analyze
  - deploy

image: node:14

build:
  stage: build
  artifacts:
    paths:
      - build
      - node_modules
    expire_in: 1 day
  before_script:
    - npm ci
  script:
    - npm run compile

test:
  stage: test
  needs:
    - job: build
      artifacts: true
  artifacts:
    paths:
      - coverage
      - reports
    reports:
      junit:
        - reports/junit_report.xml
  script:
    - npm run test

## Sonarqube configuration Documentation
## https://docs.sonarqube.org/8.9/analysis/analysis-parameters/

sonarqube:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_PROJECT: $CI_PROJECT_NAME
    SONAR_HOST_URL: https://sonarqube.intility.no
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  allow_failure: true
  script:
    - sonar-scanner
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.projectKey=$SONAR_PROJECT
      -Dsonar.projectName=$SONAR_PROJECT
      -Dsonar.qualitygate.wait=true
      -Dsonar.scm.provider=git
      -Dsonar.projectBaseDir=.
      -Dsonar.sources=src
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      -Dsonar.tests=__tests__
      -Dsonar.links.ci=$CI_PIPELINE_URL
      -Dsonar.links.scm=$CI_PROJECT_URL
      -Dsonar.exclusions=__tests__
      -Dsonar.coverage.exclusions=__tests__
  only:
    - master
    - main
    - tags

npm-audit:
  stage: analyze
  variables:
    AUDIT_FILENAME: reports/npm-audit-report.json
  script:
    - npm audit --json |& tee $AUDIT_FILENAME
  allow_failure: true
  artifacts:
    paths:
      - $AUDIT_FILENAME

.deploy_base:
  stage: deploy
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_COMMIT_SHA: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

deploy_image_qa:
  extends: .deploy_base
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_TAG
      --destination $IMAGE_TAG_COMMIT_SHA
  only:
    - qa

deploy_image:
  extends: .deploy_base
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $IMAGE_TAG
      --destination $IMAGE_TAG_COMMIT_SHA
  when: manual
  only:
    - master
    - main
