apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart.fullname" . }}
  {{- with .Values.ingressTenant }}
  labels:
    ingress-tenant: {{ .Values.ingressTenant }}
  {{- end }}
spec:
  host: {{ .Values.route }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "chart.fullname" . }}
    weight: 100
  wildcardPolicy: None
