apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart.fullname" . }}
  {{- if hasSuffix "apps.intility.com" .Values.route }}
  labels:
    ingress-tenant: shared-services
  {{- else if hasSuffix "apps.cust.intility.com" .Values.route }}
  labels:
    ingress-tenant: customer
  {{- else if hasSuffix "apps.aa.intility.com" .Values.route }}
  labels:
    ingress-tenant: aa
  {{- else if hasSuffix "apps.int.intility.no" .Values.route }}
  labels:
    ingress-tenant: aa
  {{- end }}
spec:
  host: {{ .Values.route }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "chart.fullname" . }}
    weight: 100
  wildcardPolicy: None
